name: Code Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftlint --reporter github-actions-logging
